package dockerfile

import (
	"github.com/charbonats/microbuild/v1/config"
)

const pipCacheMount = "--mount=type=cache,target=/root/.cache"
const aptCacheMount = "--mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt"
const sshMount = " --mount=type=ssh,required=true"

var defaultEnvs = map[string]string{
	"PIP_DISABLE_PIP_VERSION_CHECK": "1",
	"PIP_NO_WARN_SCRIPT_LOCATION":   "0",
	"PIP_USER":                      "1",
	"PYTHONPYCACHEPREFIX":           "$HOME/.pycache",
}

var defaulLabels = map[string]string{
	"org.opencontainers.image.description": "autogenerated by microb",
	"moby.buildkit.frontend":               "microb",
	"microb.version":                       "v1",
}

func Microb2Dockerfile(c *config.Config) string {
	dockerfile := buildStage(c)
	dockerfile += runStage(c)

	return dockerfile
}
